---
- hosts: all
  become: yes
  tasks:
  - name: updating the packages
    apt:
      update_cache: yes
  - name: installing tomcat
    apt:
      name: tomcat7
      state: present
  - name: restating tomcat7
    service:
      name: tomcat7
      state: started
  - name: deploying sample war file into tomcat webapps folder
    get_url:
      url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
      dest: /var/lib/tomcat7/webapps/